USE ADVANCED_SQL_DB;

SELECT * FROM EMPLOYEES;

-- Use of SQL Window Functions

-- Compare each employee's salary to their department's average salary

SELECT
	D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
    E.SALARY AS EMPLOYEE_SALARY,
    AVG(E.SALARY) OVER(PARTITION BY D.DEPARTMENT_NAME) AS DEPT_AVG_SALARY,
    E.SALARY - AVG(E.SALARY) OVER(PARTITION BY D.DEPARTMENT_NAME) AS VARIANCE
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY
	D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID;

-- EXAMPLE OF USING CTEs (Common Table Expression)
WITH BASE_TABLE AS
(SELECT
	D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
    E.SALARY AS EMPLOYEE_SALARY,
    AVG(E.SALARY) OVER(PARTITION BY D.DEPARTMENT_NAME) AS DEPT_AVG_SALARY
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY
	D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID)

SELECT
	B.*,
    B.EMPLOYEE_SALARY - B.DEPT_AVG_SALARY AS VARIANCE
FROM BASE_TABLE AS B;


-- EXAMPLE OF USING SUBQUERY TO DO THE SAME TASK
SELECT
	B.*,
    B.EMPLOYEE_SALARY - B.DEPT_AVG_SALARY AS VARIANCE
    FROM
(SELECT
	D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
    E.SALARY AS EMPLOYEE_SALARY,
    AVG(E.SALARY) OVER(PARTITION BY D.DEPARTMENT_NAME) AS DEPT_AVG_SALARY
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY
	D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID) B;
    
-- SQL ORDER IF EXECUTION
-- > SUBQUERY
-- > FROM
-- > JOINING
-- > WHERE CLAUSE
-- > GROUP BY
-- > AGGREGATE FUNCTIONS
-- > SELECT

-- MoM (Month over Month) Growth using Value Window Functions (LAG)

SELECT
	YEAR(O.ORDER_DATE) AS SALES_YEAR,
    MONTH(O.ORDER_DATE) AS SALES_MONTH,
	SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT)) AS CM_SALES,
    LAG(SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT))) OVER(ORDER BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE)) AS PM_SALES,
    SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT)) - LAG(SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT))) OVER(ORDER BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE))
    AS DELTA,
    (SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT)) - LAG(SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT))) OVER(ORDER BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE))) /
    LAG(SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT))) OVER(ORDER BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE)) * 100.0  AS MOM_GROWTH
FROM ORDERS O
LEFT JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
GROUP BY 1, 2
ORDER BY 1, 2;


WITH BASE_TABLE AS
(SELECT
	YEAR(O.ORDER_DATE) AS SALES_YEAR,
    MONTH(O.ORDER_DATE) AS SALES_MONTH,
	SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT)) AS CM_SALES,
    LAG(SUM(OI.UNIT_PRICE*OI.QUANTITY*(1-OI.DISCOUNT))) OVER(ORDER BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE)) AS PM_SALES
FROM ORDERS O
LEFT JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
GROUP BY 1, 2
ORDER BY 1, 2)

SELECT
	B.*,
    CM_SALES - PM_SALES AS MOM_DELTA,
    (CM_SALES - PM_SALES) / PM_SALES * 100.0 AS MOM_GROWTH
FROM BASE_TABLE AS B;
